name: update parsers info

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    name: update parsers info
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for changes
        id: parsers
        shell: bash
        run: |
          # install nvim-treesitter
          git clone --depth=1 'https://github.com/nvim-treesitter/nvim-treesitter'
          echo "RELEASE_TAG=v$(git --git-dir ./nvim-treesitter/.git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

          # install neovim
          wget 'https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz'
          tar -xzf nvim-linux64.tar.gz
          rm nvim-linux64.tar.gz

          # update parsers.json
          ./nvim-linux64/bin/nvim --headless -u ./init.lua -c 'q'
          cat parsers.min.json | jq -M -S --indent 3 . > parsers.json

          # check if parsers have changed
          ([[ -f ./changes.json ]] && echo "CHANGED=true" || echo "CHANGED=false") >> $GITHUB_OUTPUT

      - name: Update CHANGELOG.json
        if: steps.parsers.outputs.CHANGED == 'true'
        shell: bash
        run: |
          cat ./CHANGELOG.json | jq -M --indent 3 "[{
            tag: \"${{ steps.parsers.outputs.RELEASE_TAG }}\",
            url: \"https://raw.githubusercontent.com/KevinSilvester/nvim-treesitter-parsers/${{ steps.parsers.outputs.RELEASE_TAG }}/parsers.min.json\",
            date: \"$(date -u +"%F %T %Z")\",
            changes: $(cat ./changes.json)
          }] + ." > ./CHANGELOG.tmp.json

          rm CHANGELOG.json changes.json
          mv CHANGELOG.tmp.json CHANGELOG.json

      - name: Commit changes
        if: steps.parsers.outputs.CHANGED == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[CI: UPDATE PARSERS]"
          tagging_message: "${{ steps.parsers.outputs.RELEASE_TAG }}"
